### PR TITLE
loading steps dropdowns in the analysis page

### PR DESCRIPTION
**Pull request by eperedo**
### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/869498wnf

### :memo: Implementation

- [x] Loading dropdowns data in the AnalysisPage component instead each step.

### :video_camera: Screenshots/Screen capture

[Data-Quality_loading_steps.webm](https://github.com/EyeSeeTea/data-quality-dev/assets/461124/fa8deeff-014e-4ab8-b8bb-307d20d90bb9)

### :fire: Notes to the tester

#869498wnf

### CODE REVIEW

**Comment by ifoche** [comment]
Task linked: [CU-869498wnf DQ: When moving across Steps, some steps are rendered with a 'Loading' page](https://app.clickup.com/t/869498wnf)

**Review by Ramon-Jimenez — APPROVED** [review]
Thx @eperedo

**Comment by Ramon-Jimenez** [comment]
Please @eperedo  address the conflict so I can merge this. Thanks!

**Comment by eperedo** [comment]
> Please @eperedo address the conflict so I can merge this. Thanks!

Done.

**Pull request merged**
